### ISSUE TITLE
camel-raspberrypi component must run test with fork mode

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#10]
In real life, we cannot reuse the same pin.
pi4j implementation is quite difficult to emulate

**Comment by hekonsek** [comment]
Can you elaborate a little bit on this one, Greg?

**Comment by hekonsek** [comment]
Greg, what this task is about? I'm not sure if I get it :) .

**Comment by hekonsek** [comment]
Closing this one then. Feel free to reopen if we need to work on this.
