### ISSUE TITLE
Migrate Gateway heartbeats from the Camel interceptors to the recipient list

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#107]
Currently we trigger heartbeats via Camel trigger route. Then we wire into that route using interceptors (for example for MQTT heartbeats). This approach doesn't work well from the operations/management point of view. Routing logic added by the interceptors is not treated as the route, so we can't easily monitor it, nor stop/start/suspend, etc.

We should use recipient list instead of the interceptors. Recipient list allows for dynamic, plugin-like, route splitting while it keeps the semantics of the routes.

**Comment by gautric** [comment]
via a system env placeholder ?

**Comment by hekonsek** [comment]
That would be one option. I'm also thinking about using Vert.x event bus for this purpose. The heartbeats source (timer) will send the event to the event bus topic - then you can register various components that subscribe to this topic and can react on the received heartbeat event (for example logger listener, MQTT listener, LED listener, etc).

**Comment by hekonsek** [comment]
Closing old tickets.
