### ISSUE TITLE
Add GPS position consumer to the Raspberry Pi component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#11]

**Comment by gautric** [comment]
do you mean GPS ?

**Comment by gautric** [comment]
Already, I am working on I2C Endpoint w/ Consumer and Producer stuff

**Comment by hekonsek** [comment]
Yes, GPS :)

**Comment by gautric** [comment]
relation w/ #14

**Comment by jkirklan** [comment]
Would it be possible to route a message to devices that are within a certain distance of a GPS location?   This would be big in logistics...

**Comment by hekonsek** [comment]
Yes. This component is a part of the puzzle.

We can use this component to store the current device coordinates. With camel-paho component we can listen for the notifications from the server. We will be able to use server-side Fabric8 message store cloudlet (#26) as a source for (#36) geofencing cloudlet. Goefencing cloudlet will then tell us which devices are within the geofence - so we could send messages to them.

I have a prototype of this kind of demo on my local machine. I need to polish it and push to the camel-labs master. I will keep you in the loop.

**Comment by hekonsek** [comment]
Done - https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/mini/gps.html .
