### ISSUE TITLE
Performance tester should be executable as a Docker process

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#118]
Ideally you should be able just to connect your device to the local network and execute the following command:

    docker run --net=host -v /tmp/gateway-performance:/tmp/gateway-performance -t camellabs/performance-tester

After the execution of the command above, the performance diagrams should be located in the `/tmp/gateway-performance` directory.

**Comment by rimolive** [comment]
The problem with running as a docker process is for devices that don't provide docker support. There should be an option to run as a script too (or programmatically).

**Comment by hekonsek** [comment]
Actually I plan to remove performance tester from Rhiot. I don't want us to focus on gateway sizing anymore.
