### ISSUE TITLE
Create Rhiot IoT devKit setup

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#12]
It will be nice to specify the reference Raspberry Pi hardware setup that developers can easily assemble. It should contain a "shopping list" like:

- RPi B+ 2 device
- power plug
- GPS (optional)
- temperature sensor (optional)
- button and two wires (optional)

We should also provide the instructions how to assemble this setup.

We should also provide the default Camel jar application that can be deployed to that device. It will detect sensors attached to the device and forward these messages to the default message broker using MQTT.

The idea is that you could:

- buy hardware from list
- wire it together using our instructions
- deploy predefined router jar to the device
- start MQTT server
- enjoy the sensor data being collected by Raspberry Pi and forwarded to the MQTT broker

**Comment by hekonsek** [comment]
@ajurasz Wanna help with this one? :)

**Comment by ajurasz** [comment]
@hekonsek sure :)

BTW I found pretty nice and elegant example [1] of such devKit in case we will look for some inspiration. 

[1] https://projects.drogon.net/raspberry-pi/gpio-examples/

**Comment by gautric** [comment]
I did some example (GPIO only) http://gautric.github.io/blog/2015/04/03/apache-camel-raspberrypi-integration.html

**Comment by hekonsek** [comment]
Greg, actually I was thinking about using your setup as a base for the kit :) . Maybe just add a temperature sensor there :) .

**Comment by hekonsek** [comment]
@gautric How did you create those fancy RPi GPIO wiring diagram? :) I'd like to create something similar!

**Comment by gautric** [comment]
@hekonsek Fritzing is your friend ;-) http://fritzing.org/home/

**Comment by hekonsek** [comment]
@gautric Oh cool, I got it. Great thanks! @ajurasz created a base for the devKit based on the example from your blog. We've just added the temperature sensor there. Now I'm trying to document it :) .

**Comment by hekonsek** [comment]
This is supported by https://rhiot.gitbooks.io/rhiotdocumentation/content/performances/index.html#hardware-profiles .
