### ISSUE TITLE
Create camel-serial component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#13]
Geert Schuring (@geertschuring) declared that he is working on the camel-serial component based on the rxtx library. @gautric Maybe you two can collaborate on this? I know that you have started some work on the camel-serial as well.

**Comment by geertschuring** [comment]
Hi @gautric, shall we discuss what we both have at this point?

**Comment by gautric** [comment]
pi4j (1.0 and 1.1) and deviceio (UART) both provide serial port connector for raspberry (arm)

**Comment by geertschuring** [comment]
I guess we'll have to let the camel-serial component figure out whether its on a raspberry-pi or not, and use the appropriate library to read from the serial port.

**Comment by gautric** [comment]
serial port can be used directly via javac.comm api : http://docs.oracle.com/cd/E17802_01/products/products/javacomm/reference/api/

**Comment by gautric** [comment]
Add Serial Support #110

**Comment by hekonsek** [comment]
Closing this one for a while. Feel free to reopen it if you would like to contribute the component.
