### ISSUE TITLE
Prepare new logo for Rhiot

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#142]
Hi Greg,

As we are not supposed to use the Camel logo anymore, may you can come up with some new logo for us? Considering my graphics skills, you don't want me to create the logo, believe me... ;) .

**Comment by davsclaus** [comment]
I think a Camel in the logo would be fine, as ASF only has (tm) on their own official Apache Camel logo.

**Comment by davsclaus** [comment]
But a new logo that is more tech and iot'sh is likely better

**Comment by hekonsek** [comment]
I would avoid using Camel in logo to cut ASF speculations that we are stealing the trademark from them. I would also avoid Red Hat or JBoss stuff being included in the logo. IMHO the best option would be to have some fancy, universal logo not associated with anything except the IoT.

**Comment by hekonsek** [comment]
I have replaced our lovely Camel logo with some CreativeCommons cruise control icon from the Wikipedia. This is only a temporary change until we get the real logo :) .

**Comment by hekonsek** [comment]
Used new logo created by Greg. Kudos!
