### ISSUE TITLE
See what we can do with a C.H.I.P., or a bunch of them...

### ISSUE THREAD

**Issue by geertschuring** [rhiot/rhiot#166]
See https://www.kickstarter.com/projects/1598272670/chip-the-worlds-first-9-computer

**Comment by hekonsek** [comment]
Interesting!

On Fri, Aug 7, 2015, 16:07 Geert Schuring <notifications@github.com> wrote:

> See
> https://www.kickstarter.com/projects/1598272670/chip-the-worlds-first-9-computer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/166>.
>
-- 
Henryk Konsek
http://about.me/hekonsek
