### ISSUE TITLE
Create camel-spi component 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#17]

**Comment by ajurasz** [comment]
@gautric I'm in the process of reading air sensor data (see #302 ) to do this in the first step I need to use ADC like MCP3008 [1]. To be able to do this I have created pi4j-spi component (it works basically the same way as pi4j-i2c component just implementing different interface) and driver for MCP3008. And this is enought to handle my use case but if I would like to add this to master I need to add implementation to <code>SpiProducer</code> and <code>SpiConsumer</code> as they do nothing right now. 

First question can we continue the work under this thread or should I create new issue dedicated to pi4j-spi component?
Second question, do you have any suggestions on how to implement producer and consumer?


[1] https://www.adafruit.com/products/856

**Comment by hekonsek** [comment]
Greg, any thoughts on this?

**Comment by gautric** [comment]
@hekonsek we gonna implements  spi component on pi4j component
`pi4j-spi`

**Comment by gautric** [comment]
we can close this thread

**Comment by hekonsek** [comment]
@ajurasz Are you OK with closing the thread, Arek?
