### ISSUE TITLE
Build errors / failed test rhiot 0.1.1 ?

### ISSUE THREAD

**Issue by rwijngaa** [rhiot/rhiot#199]
Hi guys,

Great work & initiative on bringing camel to iot (amongst others) !
Anyway, i tried several options to build rhiot and got some small issues when building.
Any insights?

-- java 1.8.0_40, mvn 3.1.1
-- git clone on mac and mvn clean install
WARNING] The POM for org.codehaus.groovy:groovy-eclipse-compiler:jar:2.9.1-01 is missing, no dependency information available

--- docker based build:
Failed tests:
  NetworksTest.shouldReachHost:39 The subject was expected to be true, but was false

**Comment by hekonsek** [comment]
Hi Rino,

I am glad you like the project :)

I am out of the laptop for the weekend. But I will help you with build as
soon as I am back home :) .

Cheers!

On Sat, Sep 19, 2015, 20:22 Rino <notifications@github.com> wrote:

> Hi guys,
>
> Great work & initiative on bringing camel to iot (amongst others) !
> Anyway, i tried several options to build rhiot and got some small issues
> when building.
> Any insights?
>
> -- java 1.8.0_40, mvn 3.1.1
> -- git clone on mac and mvn clean install
> WARNING] The POM for
> org.codehaus.groovy:groovy-eclipse-compiler:jar:2.9.1-01 is missing, no
> dependency information available
>
> --- docker based build:
> Failed tests:
> NetworksTest.shouldReachHost:39 The subject was expected to be true, but
> was false
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/199>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by levackt** [comment]
Getting the same this morning on my local, though I get past this error from a docker-machine in the us or europe and manage to build.
FWIW my local docker-machine gets a ping of half a second to rhiot.io though mind that I'm in South Africa, strangely the test passes in the IDE and fails in maven.
I don't know if you use docker but perhaps you can try that instead of maven for now.

 +1 on the great work, big thanks.

**Comment by hekonsek** [comment]
Hi guys,

I have changed [1] the network test, so it is executed optionally only when your machine can access the rhiot.io host. This is a kind of the optional test, so such condition is perfectly acceptable. 

Thanks for catching this! Can you guys give it a try now?

Cheers!

[1] https://github.com/rhiot/rhiot/commit/8516810a53bcaf139c7f7dc9e9d7d022595ad592

**Comment by levackt** [comment]
Works for me, thanks.

**Comment by rwijngaa** [comment]
Yep, works for me too!. Thanks!

**Comment by hekonsek** [comment]
Closing then. Great to hear that it works now!

Thanks for reporting, guys!
