### ISSUE TITLE
Add producer to the camel-gpsd component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#227]
It should be possible to read GPS coordinates on demand, via producer. For example:

    from('jms:readGps').to('gpsd:gps');

**Comment by hekonsek** [comment]
@levackt Would you like to implement this one? If not, I will be happy to do it :) . In general it is good to have the ability to call the endpoint as the producer, so you can poll for example GPS on demand, not only via scheduler.

**Comment by levackt** [comment]
Cool idea and you know I want this ticket so leave it to me please :)
Have something half-baked on the shelf, will check it out tomorrow.

What behaviour do you expect if it's local and there's no daemon running?

**Comment by hekonsek** [comment]
Well, we should move the logic responsible for setting up GPSD to the endpoint (currently it is in the consumer). So basically producers and consumers should not be started until endpoint is started. Basically all you have to do is to move GPSD daemon startup process from consumer#start to endpoint#start.

BTW `KuraWifiProducer` and `KuraWifiConsumer` presents similar approach. I.e. the same operation in consumer (polling) and producer (on demand).

**Comment by levackt** [comment]
gpsd is already set up in the endpoint, it used to be in the component.
But I get the idea, in progress...

**Comment by levackt** [comment]
also done

**Comment by hekonsek** [comment]
Many thanks Taariq! You are awesome :) .
