### ISSUE TITLE
Gpsd consumer should offer both listener-based and scheduled API

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#228]
Currently we support only listener consumers i.e. we consume all the GPS events with Camel. In many cases however we would prefer to poll single GPS coordinates pair from time to time. For example every 5 seconds. This is pretty common case as usually you don't need such GPS precision, while you prefer not to overflow device with too many redundant messages.

I would like to have `?scheduled=true` option in GPSD endpoint. If this option is set to `true`, we should create scheduled polling consumer. If `scheduled=false` (default), we should use listeners, just as we do now.

It means that we should provide two consumer implementations and return one of them when calling `GpsdEndpoint#createConsumer(...)`.

**Comment by hekonsek** [comment]
@levackt The another one that might be interesting for you :) . Let me know if you want to adopt it, otherwise I can implement it.

**Comment by levackt** [comment]
No doubt! Adopted and done :)

**Comment by hekonsek** [comment]
Awesome, thanks!
