### ISSUE TITLE
Move GPSD daemon restart to the component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#230]
Hi @levackt,

I've been thinking about this, and daemon restarting logic should be in component, not in endpoint.

Currently if your create three routes like...

    from("timer:foo").to("gpsd:foo");
    from("timer:bar").to("gpsd:baz");
    from("timer:baz").to("gpsd:bar");

...you will end up with GPSD being restarted three times, as three endpoints will be created. This is usually not what users want.

I propose to move the restart logic to the `GpsdComponent#start` then. What do you think?

**Comment by levackt** [comment]
Yeah you're right, just wonder if the component will know if it's a local endpoint to start the daemon. That's how it ended up in the endpoint.
Can probably use the component's createEndpoint to decide, will check it out.

**Comment by hekonsek** [comment]
Oh, I get it now. You are right.

We can have two Countdown Latch instances in the gpsd component - "starting" and "started" The first endpoint started be Camel context will decrease the "starting" latch to indicate to the other endpoints that those should not try to restart the GPSD, but only wait until "started" latch is unblocked. As soon as the first endpoint finishes restarting the gpsd, the "started" latch is released and all the endpoints can start running.

What do you think?

**Comment by levackt** [comment]
I ran with this, please confirm the logic.
What I observed when starting multiple endpoints is that Camel will start
each endpoint one at a time and wait until it's done starting, in turn the
endpoint will wait for the component to restart the daemon if it's a local
endpoint, so the latch may be overkill.
Of course let me know if you hear the alarm bells ringing or see some
improvement.

**Comment by hekonsek** [comment]
Looks good. Closing!
