### ISSUE TITLE
Replace io.rhiot.component.gps.gpsd with io.rhiot.component.gpsd

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#233]
There is no need to have shared `gps` package anymore, as GPSD is supposed to cover all the GPS units.

**Comment by hekonsek** [comment]
@levackt Would you mind doing this little refactoring? If not, I can handle this.

**Comment by levackt** [comment]
No probs

**Comment by hekonsek** [comment]
Many thanks Taariq!
