### ISSUE TITLE
camel-webcam component

### ISSUE THREAD

**Issue by levackt** [rhiot/rhiot#239]
Would be cool to have a webcam, for one thing, the spy-machine #209 will need a spycam. :)

Other use cases that come to mind include motion detection which can trigger storing the image or uploading to the cloudlet, or you could use it for barcode scanning and a host of other things.

I tried the laptop webcam as well as an old EyeToy I have lying around.

The component supports polling the webcam for an image, ie producer, or scheduled for timelapse images, or waits for motion. 
There's WebcamVerticle which uses the default scheduled consumer taking a frame per second.

Examples:
Take a single pic
from("jms:cam").to("webcam:cam")

Scheduled (take a pic every 5 seconds)
from("webcam:cam?scheduled=true&consumer.delay=5000").to("mock:foo")

Motion (take a pic every half-second and compare for change/motion.
from("webcam:motion").to("mock:foo")

The library is from http://webcam-capture.sarxos.pl/  and the licence looks ok to a non-lawyer.

**Comment by thberger** [comment]
Will this component also support the official camera module? (https://www.raspberrypi.org/products/camera-module)

**Comment by hekonsek** [comment]
Good point! @levackt, do you know something about it?

**Comment by levackt** [comment]
It will indeed, and might already, but I'll wait for the hardware to confirm.
If I'm lucky I have it tomorrow, more likely next week.

While I'm here let me update with where I'm at with this;
- barcode demo is done, thanks to camel-barcode it's as simple as ".unmarshal(barcode)" and you have a barcode scanner, enrich with gps coords for logistics bliss.

- live streaming with camel-websocket, in progress.
This already works great in my test project even at max framerate and multiple browsers, on my local network of course, but I'm having classpath trouble in Rhiot with Jetty, same camel version so it's weird. 
I took a stab at upgrading Rhiot to Camel 2.16 but that turned out to be too much of a side-mission at the moment so I chickened out for now.

- webcam cloudlet 
I'm still thinking about what we want from the cloudlet, eg same as GPS where we write to file on the device and forward to the cloudlet if enabled, cloudlet will then save to mongodb for later review and push to websocket subscribers. 
That sound about right? Do we want the mongodb stuff at all, what do you guys have in mind for a cloudlet?

- video is on the backburner but will also be supported, for instance to start recording video in max resolution for some predetermined time when motion is detected.

**Comment by gautric** [comment]
we could create an  tested webcam list,
stay tuned ;-)

**Comment by thberger** [comment]
Hi @hekonsek  and @gautric,

that sounds very good. I already have that Pi Camera Module at home. Also the use cases you mention sound very reasonable to me. Especially starting a route when motion is detected. So I guess I can give it a try by building a route like in your examples above using the latest rhiot master?

Best

**Comment by gautric** [comment]
@thberger please take a look to my last post here 
http://gautric.github.io/blog/2015/10/22/rhiot-0.1.2-camel-webcam-macos-x.html

**Comment by levackt** [comment]
Nice one, relieved it worked for you :)
Thomas you're welcome to try the mod and if there's a driver error please let me know, I'm getting around to the driver stuff but if needed I'll push it forward.
It works on my Pi too but I don't have the mod yet, so it's possible it only works for USB devices on the Pi, and could appear to hang while it looks for your device, might need a timeout there, I'll check it out.
My mod arrives soon, along with Bright Pi which is a lighting mod, oh and a sense hat so I can join in the sense hat adventure coming soon :)

The component will support multiple cameras next time I push, its not that unusual to have different types of cameras, anyway it's in the pipeline along with some refactoring and whatnot.
I figure the cloudlet can then get notified of webcams available and also status changes, you may want to respond to an offline camera somehow, perhaps with a recipient list / dynamic toD in the route.

Cheers!

**Comment by hekonsek** [comment]
@thberger the webcam component made it into 0.1.2 release, so you can use it or the master.

@levackt I will come back to you soon with some ideas regarding the image cloudlet.

**Comment by thberger** [comment]
Hi guys,

good news: The webcam-component basically works with the Raspberry Pi Camera Module. But I had to do some extra work:

1. It is important that a specific kernel module for the v4l2 driver is loaded on the Pi. By default, this is not the case, but sudo modprobe bcm2835-v4l2 works.

2. I had to add com.github.sarxos:v4l4j to the classpath. It is not declared as Maven dependendy of the webcam module, is there a reason for that? I also need this library when I tried with my MacBook's iSight camera.

If this is done, I am able to capture images with the route. However, I have problems to start the application again, then it fails with an exception:

au.edu.jcu.v4l4j.exceptions.V4L4JException: Error starting the capture

This problem can only be solved if I hard-reboot the Pi, sudo reboot doesn't work properly anymore.
Maybe I can solve some issues, I'll keep you updated!

Thomas

**Comment by levackt** [comment]
You might notice the build is broken, sorry about that, I've now disabled
the guilty tests temporarily, related to this driver issue.

After configuring as you noted as well, I get 0.1.2 as well as master to
work, I expected 0.1.2 to fail due to that missing jar as well but I'm
surprised it worked.
The modprobe won't survive restarts, I put a comment to that effect in the
readme, you should edit rc.local


Thanks for jumping in :)

**Comment by levackt** [comment]
Good news, I got the camera mod and tested it on master and 0.1.2 release.

Note that I added a section on configuring/troubleshooting the pi mod to the docs, will think more about improving that, but it's not likely something we can handle in the component unless we edit the rc.local on deploy. 

The webcam listener idea went bust, the discovery service doesn't work for some drivers so it won't be reliable,  I don't think it would have been too useful from a cloudlet point of view anyway.

Some other changes;
- changed body to type BufferedInputStream 
- made component more testable by injecting webcam 
- camera can be selected by name and defaults to the first (I still need the producer to return list of cameras so you know which name to use)
- support setting custom driver or composite driver on the component.
- nix detection in the component to try to load the "video for linux" driver, will likely rework this some more.

**Comment by levackt** [comment]
I see what you mean Thomas, the driver eventually stops working and only
the hard restart fixes it.
I updated the docs to reflect that, and here's the link to the bug;
https://github.com/sarxos/webcam-capture/issues/382

Good to be in the same boat with you again :)

**Comment by hekonsek** [comment]
As far as `modprobe` is concerned. We can make the webcam component to load that module on the component startup using `ProcessManager` and executing an appriopriate system `modprobe` command.

I also propose to add `com.github.sarxos:v4l4j` to the webcam component if it is required by the RPi webcam.

@levackt Do you agree?

**Comment by levackt** [comment]
Agreed with both. 
5 minutes ago I thought of item 1 again so we're syncing up, and item 2 is already fixed :)

**Comment by thberger** [comment]
Hi,

Taariq, good to hear that we experience the same problem with the restart. So I guess the problem is related to the driver itself and is not influenced on the used OS or Pi model? Just for information: I tested the on a Pi 1 Model B with Raspian Wheezy.

@hekonsek : Yeah, it's good if the component loads the kernel module via ProcessManger. For me as a Java developer making first steps in the IoT world, a major criteria for the choice of the framework is the independence from too many system specifics or the need to execute shell scripts up front for the solution to work.

**Comment by levackt** [comment]
Yeah for sure.
I just pushed the process manager fix and removed the modprobe from the
docs.
I'm testing the Pi2 Model B+ at the moment, I now have no trouble
restarting the gateway, or the OS with gateway running.
I first edited my rc.local to remove the modprobe on startup to make sure
it works, please see if it works for you too on the Pi 1.

**Comment by levackt** [comment]
BTW Thomas, I've still got the error in the logs about skipping the H264
format but it doesn't stop the webcam from working, if that's the case for
you too then I'll remove the other note from the docs as well.
If it's not the case I'll dive back in and hopefully reproduce it again, or
hopefully not :)

**Comment by levackt** [comment]
Sorry Thomas, it only works when I have 2 cameras attached, when it's only
the mod the error persists so just the modprobe issue is fixed.
The hard reboot still applies for now.

**Comment by levackt** [comment]
Seems like I should reconfigure the driver in the process manager as well after the modprobe, as the allowed resolution and/or format is changing between restarts which might be related to the bug. I don't know much else yet but I'll try a few more things. Hang tight :)

**Comment by levackt** [comment]
I've hopefully worked around the hard reboot in the process manager, will do some more testing and refactoring in the coming days but it's shaping up.
Give it a try whenever you get a chance please.

**Comment by thberger** [comment]
HI Taariq,

thanks for all your work. I quickly tested your code (including commit cfdb904) in my application, it does work with some limititations: First, I haveto run the camel application with root permission (e.g. sudo). Otherwise the modprobe execution will not work and `loadWebcamDriver` will hang forever in the while-loop. Additionally, a second start of the app still doesn't work for me. `Caused by: au.edu.jcu.v4l4j.exceptions.V4L4JException: Error starting the capture` and then the hard reboot problem. May I have missed something? 
Best

PS: The application I used for testing can be found here: https://github.com/thberger/camelcam.

**Comment by levackt** [comment]
Hi Thomas

Due to ticket #256 the pi user is assumed to be able to run modprobe
without sudo, can your user do this on command line?
We can probably detect that and report the error, I'll take a look.

**Comment by levackt** [comment]
While we think of something better I took a few actions;
1. partially reverted the modprobe command to what works for the Pi/debian,
"/bin/sh", "-c", "modprobe bcm2835-v4l2"
Still without sudo, @hekonsek please let me know if you can still build
2. Fail fast if modprobe permissions are insufficient to load v4l2 or no
devices are found by v4l2
3. Submitted PR to the test project to workaround the modprobe by prefixing
sudo in a custom process manager, think twice about it, it's just a
possible workaround in the meantime.
I also considered adding a component option to specify that you want
modprobe loaded as sudo, but reverted, if this is viable I'm happy to put
it back with default to false of course.

Cheers!

**Comment by hekonsek** [comment]
Do you run your RPi app as root? For now I would assume that we do so to make integration simpler. Ecipse Kura assumes the same.

BTW Ideally I'd like our components to be smart enough to even install missing packages. For example GPSD component should install GPSD server is the latter is not present.

**Comment by hekonsek** [comment]
@levackt I can build project now. So  `/bin/sh -c modprobe bcm2835-v4l2` would work for both Rpi and Ubuntu?

BTW You might consider making this command configurable on the component level. So I could do:

    WebcamComponent webcamComponent = new WebcamComponent();
    webcamComponent.setRpiWebcamLoadingCommand("modprobe myFancyModule");

**Comment by levackt** [comment]
Yeah then it works for Raspbian/Debian and Ubuntu.
I use the default pi user on Raspian which by default has passwordless sudo, so adding that command to the component will make it easier for Pi users to just use sudo, as well as use another module.
This is much more convenient than the custom process manager.

**Comment by hekonsek** [comment]
Hmmm, Can you run `/bin/sh -c modprobe bcm2835-v4l2` as user pi? Without sudo?

**Comment by levackt** [comment]
Nope, permissions error which I also use to report and break out of the loop.

**Comment by hekonsek** [comment]
Can we close this one? I believe that base version of webcam component is ready.

**Comment by levackt** [comment]
Yeah +1, closing
