### ISSUE TITLE
Test Rhiot with Java Embedded version 8 and compact profile stuff

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#24]
Java Embedded version [1] provides 3 compact profiles [2]
we could test with compact1, compact2 and compact3 profiles 

[1] http://www.oracle.com/technetwork/java/embedded/overview/index.html
[2] http://www.oracle.com/technetwork/java/embedded/resources/tech/compact-profiles-overview-2157132.html

related to #22

**Comment by hekonsek** [comment]
BTW This is also a question about how can we prepare automated tests on real devices. I think that #12 might be useful here. @ajurasz is currently preparing some base hardware setup that we can use as a base for the kit (based on @gautric blog post).

**Comment by hekonsek** [comment]
Closing for now. Let's stick to supporting Open JDK 8 for a while.
