### ISSUE TITLE
WebCam component should not use SUDO

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#256]
@levackt Using SUDO to execute modprobe hangs my system. I would use Kura approach here and assume that current user has enough privileges to run the command. I.e. run the `modprobe` without the SUDO. Playing with SUDO like that is like playing with fire :) . This is end-user responsibility to grant access to the appropriate commands to the user running the router.

**Comment by levackt** [comment]
OK thanks for fixing, sorry about the hang :)

**Comment by hekonsek** [comment]
No biggies - process management in Java is a bitch :) BTW You can consider analyzing the output from `modprobe` and logging if the driver has been loaded or not (on INFO level, as this is system-wide operation).
