### ISSUE TITLE
WebcamComponent should analyze modprobe result to ensure v4l2 module can be loaded

### ISSUE THREAD

**Issue by levackt** [rhiot/rhiot#257]

**Comment by hekonsek** [comment]
@levackt Please remember to set the milestone when closing the issue. I need this for changelog when I cut a release :) .

**Comment by levackt** [comment]
Gotcha :)

**Comment by hekonsek** [comment]
Thanks. We don't want to miss any of your enhancements in the 0.1.3 announcement :)
