### ISSUE TITLE
Create camel-openimaj for face detection

### ISSUE THREAD

**Issue by levackt** [rhiot/rhiot#260]
With face detection we can respond to humans at the webcam, for example;

from("webcam:cam1?motion=true").to("openimaj:face-detection").
                filter(body().isInstanceOf(DetectedFace.class)).log("Human detected");

**Comment by hekonsek** [comment]
Awesome!

**Comment by hekonsek** [comment]
BTW Does openimaj supports some other interesting graphic analysis patterns?

**Comment by levackt** [comment]
We might find object detection/recognition/tracking useful in general.
Would also be nice to have hand gestures to control things, and to count vehicles, people etc.
Aside from graphics it does feature extraction from audio too, although with Xuggler which is no longer maintained, in fact OpenIMAJ hasn't released since last year.

Which reminds me, there's a similar library called OpenCV/JavaCV, before I add any more Producers to camel-openimaj I'll explore JavaCV as well, maybe this component is deleted/deprecated before it's released. :)

**Comment by hekonsek** [comment]
Does OpenIMAJ support hands gestures?

**Comment by levackt** [comment]
I might have mixed that feature up with the JavaCV, besides the Kinect I don't think it's supported if at all. 
For basic hand gestures there's also the [Hover board](http://www.hoverlabs.co/raspberry/) for Raspberry/Arduino

**Comment by hekonsek** [comment]
Can we consider it done? The basic version is functional already, right?

**Comment by levackt** [comment]
Yeah I guess, can do the R&D for javacv later.

**Comment by hekonsek** [comment]
Cool. Thanks!
