### ISSUE TITLE
camel-webcam should install v4l-utils if it's not already installed

### ISSUE THREAD

**Issue by levackt** [rhiot/rhiot#261]
Raspbian now has it installed but we should cater for others too.

**Comment by hekonsek** [comment]
It will be nice to have a OSutil class which can detect what os you are
running. So components could perform different actions for different
operating systems.

On Fri, Oct 30, 2015, 07:02 Taariq Levack <notifications@github.com> wrote:

> Raspbian now has it installed but we should cater for others too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/261>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by levackt** [comment]
The installer's pretty much done, I'll wrap it up in the coming days.
Please let me know if you have any ideas or curveballs, or if there are any
problems installing/starting webcam or gpsd.

Cheers

On 31 Oct 2015, at 15:33, Henryk Konsek <notifications@github.com> wrote:

It will be nice to have a OSutil class which can detect what os you are
running. So components could perform different actions for different
operating systems.

On Fri, Oct 30, 2015, 07:02 Taariq Levack <notifications@github.com> wrote:

> Raspbian now has it installed but we should cater for others too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/261>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

—
Reply to this email directly or view it on GitHub
<https://github.com/rhiot/rhiot/issues/261#issuecomment-152736238>.

**Comment by hekonsek** [comment]
Now everything works like a charm :) .

**Comment by levackt** [comment]
Sweet, closed.
