### ISSUE TITLE
GPIOProducer more dynamic

### ISSUE THREAD

**Issue by ajurasz** [rhiot/rhiot#268]
@gautric I would suggest to make little improvement to <code>GPIOProducer</code> so that we could change pin <code>GPIOAction</code> base on message header.  Let's consider given producer:

<code>recipientList(simple("pi4j-gpio://3?mode=DIGITAL_OUTPUT&state=LOW&action=${in.header.action}"))</code>

when <code>header</code> key is changed then camel will try to register new producer but it is not allowed due to following restriction <code>Cannot create twice same output gpio</code> but if we would override action in <code>GPIOProducer</code> using value from header then I could for example turn ON/OFF led depending on some business login.

If you don't have anything against then I can make appropriate change.

**Comment by gautric** [comment]
@ajurasz no pb, feel free to update it.
but keep in mind to preserve gpio in a safe mode.

Have you ever seen my post http://gautric.github.io/blog/2015/05/20/camel-iot-labs-i2c-gpio-mqtt-lcd.html ? I am using gpio via an wire-tap EIP

**Comment by ajurasz** [comment]
@gautric ok. My change will be harmless however covered by tests.

If it comes to your post there is exactly the same mechanism I want to apply to <code>GPIOProducer</code>.

<code>exchange.getIn().setHeader(MCP23017LCD.LCD_COLOR, "GREEN");</code> and then this value is used in <code>MCP23017LCD#process</code> method

**Comment by gautric** [comment]
+1

**Comment by hekonsek** [comment]
Yay! Thanks guys!

On Thu, Nov 12, 2015, 19:03 Greg. A. <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/268#issuecomment-156185517>.
>
-- 
Henryk Konsek
http://about.me/hekonsek
