### ISSUE TITLE
Webcam tests should timeout faster

### ISSUE THREAD

**Issue by levackt** [rhiot/rhiot#279]
Currently if a webcam is available on the build machine but the component cannot open it, then the build waits for Long.MAX_VALUE.

**Comment by hekonsek** [comment]
+1

On Sat, Nov 14, 2015, 10:38 Taariq Levack <notifications@github.com> wrote:

> Currently if a webcam is available on the build machine but the component
> cannot open it, then the build waits for Long.MAX_VALUE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/279>.
>
-- 
Henryk Konsek
http://about.me/hekonsek
