### ISSUE TITLE
Migrate documentation of Camel components to GitBook

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#293]

**Comment by gautric** [comment]
rhiot gitbook is now an organisation
we can provide some access to rhiot gitbook org for gitbook user if necessary
any github user can provide modification into github repo

**Comment by hekonsek** [comment]
It means that everybody can edit our documentation?

**Comment by gautric** [comment]
just registered github or gitbook user only w/ correct grant

**Comment by hekonsek** [comment]
But the repo is still rhiot/gitbook, right? :)

**Comment by gautric** [comment]
yep, 
rhiot/gitbook stores our doc source code, rhiot gitbook generate the final html doc

**Comment by hekonsek** [comment]
OK. I get it. We can close this task then :)
