### ISSUE TITLE
Camel-kura shouldn't depend of "org.eclipse.kura.linux.net"

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#299]
In KuraAccessPointsProvider,
we import  "org.eclipse.kura.linux.net.NetworkServiceImpl;"

we cannot use camel-kura into Kura Emulator
camel-kura should be platform agnostic

**Comment by hekonsek** [comment]
What exactly is the problem?

**Comment by gautric** [comment]
we need to import "org.eclipse.kura.linux.net" into the kura emluator and get some duplicate "org.eclipse.kura.net" service.

**Comment by hekonsek** [comment]
I'm afraid I still don't get it ;)

Can you tell me what you are exactly doing and what is the exact issue you
see?

niedz., 29.11.2015 o 22:22 użytkownik Greg. A. <notifications@github.com>
napisał:

> we need to import "org.eclipse.kura.linux.net" into the kura emluator and
> get some duplicate "org.eclipse.kura.net" service.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/299#issuecomment-160472922>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by gautric** [comment]
diff --git a/components/camel-kura/src/main/java/io/rhiot/component/kura/wifi/KuraAccessPointsProvider.java b/components/camel-kura/src/main/java/io/rhiot/component/kura/wifi/KuraAccessPointsProvider.java
index cac76e1..17a9394 100644
--- a/components/camel-kura/src/main/java/io/rhiot/component/kura/wifi/KuraAccessPointsProvider.java
+++ b/components/camel-kura/src/main/java/io/rhiot/component/kura/wifi/KuraAccessPointsProvider.java
@@ -25,7 +25,6 @@
 import org.apache.camel.spi.Registry;
 import org.apache.commons.lang3.reflect.FieldUtils;
 import org.eclipse.kura.KuraException;
-import org.eclipse.kura.linux.net.NetworkServiceImpl;
 import org.eclipse.kura.net.NetworkService;
 import org.eclipse.kura.net.wifi.WifiAccessPoint;
 import org.slf4j.Logger;
@@ -68,16 +67,19 @@
     // Helpers
 
     private NetworkService resolveNetworkService(Registry registry) {
+        NetworkService ret = null;
         Set<NetworkService> servicesFromRegistry = registry.findByType(NetworkService.class);
-        if (servicesFromRegistry.size() != 1) {
-            LOG.info("Found {} Kura NetworkService instances in the registry. Creating and using custom instance then.",
-                    servicesFromRegistry.size());
-            NetworkService networkService = new NetworkServiceImpl();
-            initializeNetworkService(networkService);
-            return networkService;
+        if (servicesFromRegistry.size() == 1) {
+            ret = servicesFromRegistry.iterator().next();
+        } else if (servicesFromRegistry.size() > 1) {
+            throw new IllegalStateException(
+                    "Too many NetworkService services found in a registry: " + servicesFromRegistry.size());
+        } else {
+            throw new IllegalArgumentException("No NetworkService service instance found in a registry.");
         }
+
         LOG.info("Found Kura NetworkService in the registry. Kura component will use that instance.");
-        return servicesFromRegistry.iterator().next();
+        return ret;
     }
 
     protected void initializeNetworkService(NetworkService networkService) {

**Comment by gautric** [comment]
we gonna create an ServiceFactory

**Comment by gautric** [comment]
we can close it, camel-kura runs correctly inside the kura emulator
