### ISSUE TITLE
Create camel device-io gpio component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#3]
@gautric mentioned he works on it.

**Comment by gautric** [comment]
this component uses this lib http://openjdk.java.net/projects/dio/
Dio provides dio.jar (java lib) and dio.so (native lib)
Dio project doesn't release any artifact to maven central
we should manage our own dio.jar and dio.so repository

**Comment by hekonsek** [comment]
Please remember to document [1] the component. Thanks!

[1] https://github.com/camel-labs/camel-labs/tree/master/iot#camel-iot-components

**Comment by hekonsek** [comment]
Can we close this one in 0.0.0 release?

**Comment by hekonsek** [comment]
@gautric Ping :) We are including this in 0.0.0 or moving to 0.0.1?

**Comment by gautric** [comment]
impl for gpio ok, I have to write the doc
move to 0.0.1

**Comment by hekonsek** [comment]
OK. Thanks!

**Comment by hekonsek** [comment]
@gautric Is it done? Do we have it documented?

**Comment by gautric** [comment]
still in progress

**Comment by hekonsek** [comment]
Cool. I want to be sure we have 100% documentation coverage for our Camel components. Thanks!

**Comment by hekonsek** [comment]
Any updates on this?

**Comment by hekonsek** [comment]
Ping. Not documented component doesn't exist. :)

**Comment by gautric** [comment]
<https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/camel_components/camel_device_io_component.html>

**Comment by hekonsek** [comment]
Awesome, thanks!
