### ISSUE TITLE
Automated tests on real devices 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#30]
#12 
#24

**Comment by hekonsek** [comment]
We need to create shell commands for Kura, so we can fully automate deployments of Kura modules to RPi devices.

**Comment by hekonsek** [comment]
Let's reopen this when tools are ready.

**Comment by gautric** [comment]
perso I use https://www.weaved.com/ to connect to my RPi zero withour pb ;-)
let's try it too ;-)

**Comment by hekonsek** [comment]
We can use Brno hosting center for this purpose. That would be preferable over using some 3rd party company services :) .
