### ISSUE TITLE
Create Rhiot gateway reference architecture

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#301]
I believe we should support Kura as our primary gateway. So Rhiot gateway would be basically a set of utilities and modules around Eclipse Kura. Our goal is to provide better user experience and additional functionalities for Kura.

We also should support lightweight Rhiot gateway, which is non-OSGi subset of our Kura gateway. Its primary goal would be to provide better user experiences for the makers community and developers interested in rapidly getting into a gateway software.

While Kura gateway has been proven to be a production-ready solution, lightweight gateway is a way to go for a makers community willing to perform some rapid experiments with an IoT gateways.

**Comment by lasombra** [comment]
I agree but I believe that we should provide a better documentation and quickstarts than Kura.

**Comment by gautric** [comment]
@hekonsek, yep Kura is a strong and robust platform, 
I think we could invest on Kura platform, and provide best effort for non-OSGI/Kura gateway 

@lasombra I am writing a new blog post, stay tuned ;-)

**Comment by lasombra** [comment]
@gautric Good stuff :)

Couldn't we, maybe, add a layer to easily deploy non-OSGI stuff on top of the OSGI container?

**Comment by hekonsek** [comment]
@lasombra Yeah, our goal here is to improve user experience, so we definitely would like to have better docs and examples.

**Comment by hekonsek** [comment]
@gautric Looking forward to seeing the blog post!

**Comment by hekonsek** [comment]
@lasombra Adding extra layer will be difficult, as OSGi internal will leak that abstraction anyway. I was rather planning to just support as much as possible of Kura bits outside of OSGi.

**Comment by hekonsek** [comment]
Done.
