### ISSUE TITLE
Build information page results in "page not found"

### ISSUE THREAD

**Issue by tplevko** [rhiot/rhiot#309]
When I followed the "If you want to build the project yourself, read this document." there is page not found: https://github.com/rhiot/rhiot/blob/master/docs/building.md

**Comment by gautric** [comment]
hi @tplevko,

thx for pointing this error,

[building info can be found here ](https://rhiot.gitbooks.io/rhiotdocumentation/content/building/index.html)

**Comment by hekonsek** [comment]
@gautric Many thanks for handling this!
