### ISSUE TITLE
Test RHIOT w/ Pi Zero

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#320]
got mine in few days ;-)

**Comment by hekonsek** [comment]
Yay!

On Mon, Dec 14, 2015, 13:06 Greg. A. <notifications@github.com> wrote:

> got mine in few days ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/320>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by gautric** [comment]
Rhiot project works fine
see my blog
