### ISSUE TITLE
RFE: Add option to gateway-deployer for other network

### ISSUE THREAD

**Issue by PatrickSteiner** [rhiot/rhiot#321]
... just an idea ...

I run my build environment on a VM with a NAT-ed network, while my Pi is connected to my WLAN.

As of now, it seems like the gateway deployer will not find my Pi, as he scans the wrong subnet.
Would it be possible ( or make sense ) if there was a way to tell the deployer with network segment to scan?

**Comment by hekonsek** [comment]
Can you send me the example of the IP addresses and network interfaces involved into your setup? For example:

- Pi address = foo 
- laptop address = bar
- laptop interfacess = eth0, wlan0, etc
- laptop interface used = wlan0

**Comment by hekonsek** [comment]
Also keep in mind that you can specify [1] address of the device for the most of the commands (and therefore skip the network scanning):

     device-config --host 192.168.1.1 /conf foo bar

I need to emphasize this in the quickstart :) .

[1] https://rhiot.gitbooks.io/rhiotdocumentation/content/tooling/cmd.html#deviceconfig

**Comment by hekonsek** [comment]
In general I think that the best option would be to:
- improve scanner to search for all the networks available for all interfaces
- fallback to `--address` option if necessary

What do you think?

**Comment by PatrickSteiner** [comment]
I think it would be enough to mention the possibility of the --address option in the cmd-line documentation.

Maybe even in every subchapter?

**Comment by hekonsek** [comment]
I have updated quickstart documentation [1] and CMD [2]. Is it clearer now?

[1] https://rhiot.gitbooks.io/rhiotdocumentation/content/quickstarts/kura_camel_quickstart.html#Configure-Kura
[2] https://rhiot.gitbooks.io/rhiotdocumentation/content/tooling/cmd.html#kuraconfigbootdelegation

**Comment by PatrickSteiner** [comment]
much better! Thanks

**Comment by hekonsek** [comment]
Many thanks for the invaluable feedback :) .

wt., 22.12.2015 o 09:08 użytkownik Patrick Steiner <notifications@github.com>
napisał:

> much better! Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/321#issuecomment-166549554>.
>
-- 
Henryk Konsek
http://about.me/hekonsek
