### ISSUE TITLE
Documentation pointing to wrong URL

### ISSUE THREAD

**Issue by PatrickSteiner** [rhiot/rhiot#324]
When going through the documentation in 

https://github.com/rhiot/gitbook/blob/master/gateway/mini/installing.md

the links/URLs pointing to internal sections all point to outdated paths.
I have seen this for 

 "In order to install Rhiot mini gateway on one of supported gateway platforms (like Raspberry Pi with Raspbian) use Rhiot cmd tool (rhiot cmd section describes how to install Rhiot cmd)."

Potentially also true for other documents and links.

**Comment by gautric** [comment]
@PatrickSteiner thx for pointing this issue
It sould be fixed now

**Comment by hekonsek** [comment]
@PatrickSteiner Thanks for reporting. We are just in the process of migration of documentation, so some links might be broken. I will find those an correct them.
