### ISSUE TITLE
provide more flexible RHIOT_HOME env 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#339]
now user can define is own RHIOT_HOME env
if not we use RHIOT_HOME_DEFAULT

We create RHIOT_HOME only if needed

**Comment by hekonsek** [comment]
What is rhiot home? What uses this env?

On Wed, Dec 16, 2015, 12:37 Greg. A. <notifications@github.com> wrote:

> Closed #339 <https://github.com/rhiot/rhiot/issues/339>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/339#event-493361135>.
>
-- 
Henryk Konsek
http://about.me/hekonsek
