### ISSUE TITLE
rhiot command should use `docker-machine` do check docker env stuff

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#340]

**Comment by hekonsek** [comment]
+1

On Wed, Dec 16, 2015, 12:40 Greg. A. <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/340>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by gautric** [comment]
close by #343
