### ISSUE TITLE
change "if test" to "case test" for OS  (ubuntu, MacOs) interop

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#354]

**Comment by hekonsek** [comment]
Good idea. +1

On Fri, Dec 18, 2015, 14:23 Greg. A. <notifications@github.com> wrote:

> Closed #354 <https://github.com/rhiot/rhiot/issues/354>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/354#event-495817978>.
>
-- 
Henryk Konsek
http://about.me/hekonsek
