### ISSUE TITLE
Limit the number of GPSD restart retries

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#359]

**Comment by levackt** [comment]
@gautric 
Greg if you don't mind I'll claim this, just setting up gitbook to document the param then it's done.

**Comment by levackt** [comment]
I don't see how to add docs or send a PR, will check it out next time. 
Meanwhile see if the commit is cool and pop the following into the docs please, right after the GPSD Options section.  Cheers!

## Starting the GPSD process

By default, the GPSD component attempts to start the GPSD daemon every 5 seconds, it does this indefinitely until successfully started and configured.

You can configure limits on the component, eg a maximum of 3 attempts, once per minute:

    GpsdComponent gpsd = new GpsdComponent();
    gpsd.setGpsdMaxRestartAttempts(3); 
    gpsd.setGpsdRestartInterval(60000);
    camelContext.addComponent("gpsd", gpsd);

**Comment by gautric** [comment]
Your modif has been committed correctly  : 
https://rhiot.gitbooks.io/rhiotdocumentation/content/gateway/camel_components/camel_gpsd_component.html

**Comment by levackt** [comment]
Thanks, closed.
