### ISSUE TITLE
Create Geofence Cloudlet

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#36]
Geofence cloudlet should be able to consume data from message store (#26) cloudlet to provide geo-based output like:
- if given device is within the radius of the geofence
- how far from the fence is given device
- we can also use Google Static Maps API to graphically display this kid of data

I have a prototype of this cloudlet on my local machine already.

**Comment by gautric** [comment]
#71

**Comment by hekonsek** [comment]
Done.
