### ISSUE TITLE
Quickstart not starting because of "java.lang.NoClassDefFoundError"

### ISSUE THREAD

**Issue by PatrickSteiner** [rhiot/rhiot#364]
When following the quickstart ( 20.12.2015 ), I do get the following error when doing the following steps

 - build kura-camel with "mvn -U clean install"
 - scp all files to RPi
 - executed all "install ..." command via cut/paste from quickstart
 - starting last installed bundle

015-12-20 06:23:09,872 [Component Resolve Thread (Bundle 6)] WARN  i.r.q.k.c.GatewayRouter - Problem when starting Kura module io.rhiot.quickstarts.kura.camel.GatewayRouter:
java.lang.NoClassDefFoundError: sun/misc/Unsafe
        at org.apache.camel.com.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8.getUnsafe(ConcurrentHashMapV8.java:4136)
        at org.apache.camel.com.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8.<clinit>(ConcurrentHashMapV8.java:4101)
        at org.apache.camel.com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap.<init>(ConcurrentLinkedHashMap.java:221)

Any idea?

Patrick

**Comment by gautric** [comment]
hi @PatrickSteiner,
I guess you missed step [Configure Kura](https://rhiot.gitbooks.io/rhiotdocumentation/content/quickstarts/kura_camel_quickstart.html#configure-kura) of our Manual.

thx for testing

**Comment by PatrickSteiner** [comment]
Thanks @gautric for the support even on 4. advent ;-) merry christmas!

When did this command sneak into the documentation? I still remember seeing some simular with what to manually update in /opt/eclipse/kura/kura/config.ini

I'm running development from Mac os x and am still struggling to install the rhiot cmd-line command.

In the meantime. Can you tell me what to manually enter inter /opt/eclipse/kura/kura/config.ini?

**Comment by gautric** [comment]
we support our big community 24/7 :-)
please add this line to your `/opt/eclipse/kura/kura/config.ini`
```
      org.osgi.framework.bootdelegation=sun.*,com.sun.* 
```
it should be work fine after that (X finger)

**Comment by PatrickSteiner** [comment]
Yep! That was it!

Thanks
