### ISSUE TITLE
Instruction for rhiot-cmd installation unprecise

### ISSUE THREAD

**Issue by PatrickSteiner** [rhiot/rhiot#365]
For Jessie based RPi the instruction from chapter https://rhiot.gitbooks.io/rhiotdocumentation/content/tooling/cmd.html ( Before you install ) should be

------------

```
$ sudo nano /etc/ssh/sshd_config 
```

Find  entry in the Authentication section of the file that says ‘PermitRootLogin’ and change ‘without-password’ to ‘yes’.

```
# Authentication:
LoginGraceTime 120
#PermitRootLogin without-password
PermitRootLogin yes
StrictModes yes
```
---------------

Original instruction does not mention to remove the old entry and where in the file to add this statement.

**Comment by hekonsek** [comment]
Actually in CMD documentation we are suggesting that you should change your root password instead of leaving it empty:

```
If you would like to authenticate yourself as root using password, you have to change it (as a default root password is
not set):

    sudo passwd root

For Raspbian, we recommend to use the default password - `raspberry`.
```

I think that it is less likely to generate some issues with none vs empty passwords. What do you think?

**Comment by PatrickSteiner** [comment]
I was more trying to point out, what and where the changes in 

´´´
/etc/ssh/sshd_config 
´´´

needed to be made. As you where using a different notation 'PermitRootLogin yes' vs 'PermitRootLogin=yes' an unexperienced person might not know of 'PermitRootLogin=yes' is a substitute or additional parameter.

**Comment by hekonsek** [comment]
Actually I believe that you can just add `PermitRootLogin yes` anywhere in the SSHD config file. I changed the documentation to say:

```
The easiest way to use root-enabled SSH user is to enable root login at your device. In order to do it, add the following
option anywhere in the `/etc/ssh/sshd_config` file:

    $ sudo nano /etc/ssh/sshd_config 
    PermitRootLogin yes
```

Is it better now? :)

**Comment by PatrickSteiner** [comment]
Why don't you take the full '# Authentication:' section into the documentation, as shown above? That would make it much easier.

**Comment by hekonsek** [comment]
Fair enough. Added the whole section to provide the context. How does it look now?

**Comment by PatrickSteiner** [comment]
perfect!

**Comment by hekonsek** [comment]
Yay! Many thanks again!
