### ISSUE TITLE
Cloud Platform installation file script moved

### ISSUE THREAD

**Issue by ppatierno** [rhiot/rhiot#382]
Hi,

trying to execute the "bash <(curl -s https://goo.gl/nVsrg6)" command to install the cloud platform as described here https://rhiot.gitbooks.io/rhiotdocumentation/content/cloudplatform/starting.html, I received the following error : 

[ppatierno@localhost ~]$ bash <(curl -s https://goo.gl/nVsrg6)
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<HTML>'

I saw that it's due to the following output executing only the curl command : 

[ppatierno@localhost ~]$ curl -s https://goo.gl/nVsrg6
```html
<HTML>
<HEAD>
<TITLE>Moved Permanently</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Permanently</H1>
The document has moved <A HREF="https://raw.githubusercontent.com/rhiot/rhiot/master/cloudplatform/install/rhiot-cloud-platform.sh">here</A>.
</BODY>
</HTML>
```
I suppose you moved the script so the google short URL should be regenerate.

Thanks,
Paolo.

**Comment by gautric** [comment]
Hi @ppatierno 

could you add ```-L``` inside curl command ?

By advance, thx

**Comment by ppatierno** [comment]
Ok .. with -L it works. I saw you alredy updated the documentation. Thanks

**Comment by hekonsek** [comment]
Thanks for noticing and fixing!

BTW Currently we are refactoring our cloud platform to match IoT Eclipse Platform architecture. So please keep in mind that project may be slightly unstable while we doing it. Sorry for the inconvenience!

[1] https://projects.eclipse.org/proposals/iot-connector

**Comment by ppatierno** [comment]
So it means that the Cloud Platform is not usable for now ?

It seems that the device management documentation page has another error related to which is the immage to pull out ... io.rhiot/cloudlet-device/0.1.1 doesn't exist. I suppose you mean the rhiot/cloudlet-device. However I have problem to query and use the REST API.

**Comment by hekonsek** [comment]
Yes, actually I'm updating the documentation as we talk :) . The old version of backend service used REST API directly over Leshan server. Our new architecture exposes generic device management service over IoT Connector (AMQP), while REST or LWM2M protocol adapters can be used to bridge request from devices to backend service (via AMQP).

In coming days all the documentation will be updated to reflect that new architecture.

Sorry for the mess, but joining Eclipse Server Platform is a strategic move for us, so making Rhiot compatible with this new initiative is our top priority now. :)

**Comment by ppatierno** [comment]
Don't worry ... just to know so that I can avoid a waste of time on setup the cloud platform :-)

**Comment by hekonsek** [comment]
I will let you know as soon as cloud platform and device management service is refactored, documented and ready to give it a try. Should be by the end of the week. That would save you some failed attempts of bootstrapping things :) .

**Comment by ppatierno** [comment]
Thanks ;)
