### ISSUE TITLE
Create WebSocket protcol adapter

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#389]
creation ws bridge 

into rhiot-cloudplatform-adapter-websocket maven module

**Comment by hekonsek** [comment]
I would map WS web URI to AMQP channel. So `foo/bar` WS resource is mapped to AMQP `foo.bar` queue.

**Comment by gautric** [comment]
yep,

but websocket is connected protocol, we cannot change URI onfly
I have to know every URI before create websocket connector :-(

**Comment by hekonsek** [comment]
Can't you create a wildcard websocket connector with Jetty? It should be possible.

**Comment by hekonsek** [comment]
Actually I think that we don't need this adapter at all. Instead we should just use AMQ WS connector. I propose to delete this module then. And add support for WS connector to AMQ Broker [2].

We could add integration test to node suite [3] to verify that you can use WS to execute document count [4] operation.

What do you think?

[1] http://activemq.apache.org/websockets.html
[2] https://github.com/rhiot/rhiot/blob/master/spring/activemq/src/main/java/io/rhiot/spring/activemq/broker/ActivemqBrokerConfiguration.java
[3] https://github.com/rhiot/rhiot/blob/master/datastream/node/src/test/groovy/io/rhiot/datastream/node/DataStreamNodeTest.groovy
[4] https://github.com/rhiot/rhiot/blob/master/datastream/node/src/test/groovy/io/rhiot/datastream/node/DataStreamNodeTest.groovy#L31

**Comment by hekonsek** [comment]
We should also modify PaaS script (rhiot-cloud-platform) to expose default web sockets port (and start WS connector, by setting proper env when starting container).

**Comment by gautric** [comment]
do you prefer I close it and rework a new issue ?

**Comment by hekonsek** [comment]
We can keep this one. :)

śr., 13.01.2016 o 16:32 użytkownik Greg. A. <notifications@github.com>
napisał:

> do you prefer I close it and rework a new issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/389#issuecomment-171332102>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by hekonsek** [comment]
Any updates on this?

**Comment by hekonsek** [comment]
Can you add test to `DataStreamNodeTest` verifying that you can access document service websockets? And document this protocol adapter.

**Comment by hekonsek** [comment]
Any news on this?

**Comment by gautric** [comment]
not yet finished

**Comment by hekonsek** [comment]
How's the tests going? Do you need help with that?

**Comment by gautric** [comment]
doc is now ok
