### ISSUE TITLE
~/.rhiot/rcp.log is empty

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#427]
@gautric Are you sure that logging to `~/.rhiot/rcp.log` works correctly? My `~/.rhiot/rcp.log` is always empty.

**Comment by hekonsek** [comment]
This is what I see:

```
hekonsek henryberg:~ [2186]% tail ~/.rhiot/rcp.log
ECHO : 19fb0b5322d8: Pull complete
ECHO : bc688d58f25a: Pull complete
ECHO : 5edf2b722e23: Pull complete
ECHO : 83c7d8eb8422: Pull complete
ECHO : a6f097d25d32: Verifying Checksum
ECHO : a6f097d25d32: Download complete
ECHO : a6f097d25d32: Pull complete
ECHO : ddcafd948be4: Pull complete
ECHO : d87bd4eeb176: Pull complete
ECHO : ed22506fd334: Pull comple%   
```

While I'd like to see the progress of the pull.

Are you sure that your SED doesn't cut the progress out of the logs?

**Comment by hekonsek** [comment]
Also you should be appending (`>>`) not overriding (`>`) the log file.

**Comment by gautric** [comment]
yep, sorry I miss it

**Comment by gautric** [comment]
I will fix it

**Comment by gautric** [comment]
I remove dirty stuff,
I have to rework on
