### ISSUE TITLE
Create Cloud Platform quickstart

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#446]
@ppatierno I think that we might create quickstart project with following components loaded:
- REST protocol adapter
- JSON encoding
- device management service

If you would like to start playing pro grammatically with Cloud Platform, using this quickstart would be the best way to get going.

What do you think?

**Comment by ppatierno** [comment]
Of course, they are the three basic components to develop/try an end to end solution.

However, I didn't deep into metrics service yet but ... if it's related to store data received by devices (in a telemetry fashion) in a mongodb database, I think that it could be useful to have this service up and running too.

**Comment by ppatierno** [comment]
Added skeleton in quickstart : 

https://github.com/rhiot/quickstarts/tree/master/cloudplatform

The purpose will be to show how to implement a custom service to interface with IoT connector and calling it using different protocols thanks to related adapters. We'll start with HTTP REST and AMQP.

**Comment by ppatierno** [comment]
Added tests to invoke a custom service (temperature service) for storing temperature value and reading temperature threshold.
The tests use both the HTTP REST adapter and direct IoT Connector component using both parameters on URL/channel and/or body.

Documentation will be available soon.

**Comment by ppatierno** [comment]
Sorry for delay but I already wrote documentation about it ...

https://rhiot.gitbooks.io/rhiotdocumentation/content/quickstarts/cloudplatform.html

I forgot to close the issue :-)

**Comment by hekonsek** [comment]
Thanks, looks good!
