### ISSUE TITLE
Wrong folder name "pass"

### ISSUE THREAD

**Issue by ppatierno** [rhiot/rhiot#448]
Hi,
I know it's a very stupid issue but I think that even if stupid it should be fixed :-) 

Under rhiot/cloudplatform, the folder for the PaaS stuff is named "pass" instead of "paas".

Paolo.

**Comment by hekonsek** [comment]
Fixed. Good catch :) .

**Comment by hekonsek** [comment]
BTW I have granted you committer privileges. Welcome to the team :) .

**Comment by ppatierno** [comment]
Great ! Thanks ! ;-)

**Comment by gautric** [comment]
Welcome on board ;-)

**Comment by ppatierno** [comment]
Thanks !
