### ISSUE TITLE
do we should provide logback.xml file into "main" folder for this artifact

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#452]
<https://github.com/rhiot/rhiot/blob/master/cloudplatform/paas/adapters/src/main/resources/logback.xml>

@hekonsek  for testing/ test folder only isn't it ?

**Comment by hekonsek** [comment]
It should be here, as this is fat jar project. It is supposed to be run as an executable. So we need logger config for it included in a final artifact.
