### ISSUE TITLE
Building Docker images of cloud platform components

### ISSUE THREAD

**Issue by ppatierno** [rhiot/rhiot#455]
Hi all,

it's sure that I lost something but ... I see the following ...

the activemq pom.xml file is the only one with a complete docker maven plugin configuration to build the activemq docker image starting from the fatjar image (available thanks to a Dockerfile).
For all the Docker images (in the Hub) about cloud platform, I can't see any way to build the image (Dockerfile or docker maven plugin)  : for example the pom.xml file for the paas adapters has an empty docker maven plugin configuration.

Is there something I can't see ?

Thanks,
Paolo

**Comment by ppatierno** [comment]
I just found the solution in the root pom.xml file :-)

**Comment by hekonsek** [comment]
Exactly, we use the common plugin configuration. So you can just specify those properties to configure your Docker image:

         <docker.image.target>paas-adapters</docker.image.target>
        <fatjar.mainClass>io.rhiot.cloudplatform.runtime.spring.CloudPlatform</fatjar.mainClass>

Of course you can also override the configuration in your module, if you need to. However usually those two properties are just fine :) .
