### ISSUE TITLE
create GPIO/I2C/SPI DSL 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#46]

**Comment by hekonsek** [comment]
+1

**Comment by gautric** [comment]
Spec for GPIO
```
gpio(id).high().to()
gpio(id).low().to()
gpio(id).toggle().to()
from().gpio(id) #use body value
from().gpio(id).high()
from().gpio(id).low().to()
from().gpio(id).toggle()
```

Spec for I2C
```
i2c(bus,id).poll().to() "use body value
from().i2c(bus,id)
```

**Comment by gautric** [comment]
sample code here
https://github.com/apache/camel/tree/master/camel-core/src/main/java/org/apache/camel/model/rest

**Comment by gautric** [comment]
@hekonsek what do you think about creating an component (maven) like this "camel-iot-dsl" ?

**Comment by hekonsek** [comment]
Actually I prefer splitting the DSL into the more specialized modules. For example camel-iot-gpio-dsl .

**Comment by hekonsek** [comment]
Just to avoid keeping all possible DSLs in a single jar.

**Comment by hekonsek** [comment]
Hi @gautric,

@sbunciak would like to push forward the topic of the implementation-agnostic DSL / modules.

The first question is - DSL for what exactly we would like to create in the first place? GPIO? I2C?

**Comment by hekonsek** [comment]
Moving to the next release.

**Comment by sbunciak** [comment]
Hi @hekonsek,

I'm not completely familiar with the implementation details of common DSLs in Camel, however I'd first create some kind of common API/SPI that all the "connector" components (camel-pi4j, camel-bulldog) needs to implement.

As for the DSL itself, GPIO + I2C + SPI (+ UART?) will do the thing I guess. The spec by @gautric seems fine.

**Comment by gautric** [comment]
spec : https://gist.github.com/gautric/85c68f3b204398b523b1

**Comment by hekonsek** [comment]
I would start with committing camel-bulldog component first. Then creating DSL module and implementing DSL in pi4j and bulldog components. DSL is really an addition to the components. The latter can be used even without DSL - using endpoint URIs.

**Comment by hekonsek** [comment]
Closing old tickets. Feel free to reopen it you would like to contribute an actual code.
