### ISSUE TITLE
Camel Maven plugin to generate or maintain documentation

### ISSUE THREAD

**Issue by davsclaus** [rhiot/rhiot#47]
It seems like a good place to innovate on the maven plugin we eventually would need at Apache Camel to help maintain the growing number of components and their documentation.

Today ppl document their components in the source code such as a readme.md file. 

At ASF we have an old school wiki system that is cumbersome to work with.

So we have for years wanted to migrate the component docs to source code based, but that takes time.

It seems like a good place here at camel-labs to experiment with this plugin, as this project is primary hosted at github where we use readme.md files for documentation.

So for example we could let the plugin generate or keep a component list up to date
https://github.com/camel-labs/camel-labs/tree/master/iot/components

And then for each component they have their own docs as readme.md in the folder.
https://github.com/camel-labs/camel-labs/tree/master/iot/components/camel-kura

Then we can also embed the readme.md in the JAR file which then tooling also can access at runtime, such as showing from a karaf command, jmx, hawtio, or whatelse.

One idea is to let the plugin be able to

- create initial readme.md if missing
- keep parts of readme.md up to date, primary the options for component / endpoints etc.
- and then leave room for humans to add content such as tips / examples / and whatnot.

So if you add a new option to an option the plugin updates the readme.md file automatic so it becomes part of the commit.

Then over time we should also allow for adding logos and links to the project website, and more. Then the tooling can display a nice component catalog with logos for the various component they use.

**Comment by geertschuring** [comment]
Sounds good!

**Comment by hekonsek** [comment]
I like this! I will try to add such MD goal to the plugin.

**Comment by hekonsek** [comment]
Moving to the next release.

**Comment by hekonsek** [comment]
We moved documentation to GitBook - https://rhiot.gitbooks.io/rhiotdocumentation/content/cloudplatform/cloudplatform.html . 

Closing the old tickets for a while. We might open this when somebody got more time to develop the extra plugin functionality.
