### ISSUE TITLE
create camel-labs.github.io website via Github Pages

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#50]
creation of camel-labs.github.io repository needed

**Comment by hekonsek** [comment]
What I'm supposed to do here? :)

**Comment by hekonsek** [comment]
@gautric What we have to do here? :)

**Comment by gautric** [comment]
we could create an website to show and blog some cool stuff.
It could be a tutorial too

**Comment by sbunciak** [comment]
Would you mind creating a cross reference between camel-labs and
silverspoon.io web pages?

2015-05-18 22:54 GMT+02:00 Greg. A. <notifications@github.com>:

**Comment by hekonsek** [comment]
@sbunciak Linked [1] Silverspoon and Silverware at the main page.

[1] https://github.com/camel-labs/camel-labs/blob/master/README.md#iot-ecosystem

**Comment by hekonsek** [comment]
Greg, can you lead the effort of creating the page? I'm not good at this kind of stuff :) . Anyway - unassigning myself from this task.

**Comment by gautric** [comment]
replaced by https://github.com/rhiot/rhiot/issues/294 #294
