### ISSUE TITLE
Build is failling with finding io.rhiot:vertx-proton:jar:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by rimolive** [rhiot/rhiot#541]
If there are any additional repositories in settings.xml then it should be added in the docs.

**Comment by hekonsek** [comment]
It is located in sonatype snapshot repo. I will add it to the pom. Thanks
for catching this!

On Fri, Mar 11, 2016, 17:17 Ricardo Martinelli de Oliveira <
notifications@github.com> wrote:

> If there are any additional repositories in settings.xml then it should be
> added in the docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/541>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by hekonsek** [comment]
Fixed. Can you try it now? :)

**Comment by rimolive** [comment]
Now the build is working. Thank you so much!

**Comment by hekonsek** [comment]
Awesome! Glad to hear that.
