### ISSUE TITLE
Create util to check what is the current device

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#55]

**Comment by sbunciak** [comment]
We would like to include such functionality in Bulldog as well, e.g via memory lookup (like lshw). Not sure whether it's possible, though.

https://github.com/px3/bulldog/issues/23

**Comment by hekonsek** [comment]
Thanks for the update Stefan. Noted :) .

**Comment by hekonsek** [comment]
Closing this one for a while.
