### ISSUE TITLE
Add MQTT-SN support

### ISSUE THREAD

**Issue by rimolive** [rhiot/rhiot#554]
Implement MQTT-SN support for Wireless Sensors Network. Specification is located in: http://mqtt.org/new/wp-content/uploads/2009/06/MQTT-SN_spec_v1.2.pdf

**Comment by hekonsek** [comment]
We're moving Kura support from Rhiot into Eclipse Kura project umbrella. Feel free to report issues here - https://github.com/eclipse/kura .
