### ISSUE TITLE
Create camel-temperature component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#56]
The component should make sure that:

- `/boot/config.txt` file has been properly changed
- `sudo modprobe w1-gpio` and `sudo modprobe w1-therm` are loaded
- read temperature from the  `/sys/bus/w1/devices/28-*/w1_slave` 

This is an alternative for using the gpio component directly.

**Comment by sbunciak** [comment]
Hi, 
we have already a student working on this component: https://github.com/px3/silverspoon/issues/5. 

Btw. reading the temperature from /sys/bus/w1/devices/28-*/w1_slave is already implemented in Bulldog: https://github.com/px3/bulldog/blob/devel/bulldog-devices/src/main/java/io/silverspoon/bulldog/devices/sensors/DS18B20TemperatureSensor.java

**Comment by hekonsek** [comment]
Actually I hoped you will write something like this! :D Let me take a look at this.

**Comment by hekonsek** [comment]
I'm wondering how to approach this. I don't want to pull all the Bulldog dependencies into the camel-temperature component. Can you guys consider donating that fancy class sensor to Camel Labs camel-temperature component?

**Comment by hekonsek** [comment]
Maybe the student you mentioned could work on the camel-temperature component here at Camel Labs?

**Comment by hekonsek** [comment]
I could help him/her in the case of Camel-related problems :) .

**Comment by hekonsek** [comment]
BTW Ping @ajurasz .

**Comment by hekonsek** [comment]
@sbunciak What do you think about developing that component and adding `DS18B20TemperatureSensor.java` here to the Camel Labs? Also when do you expect to have this done by the student you mentioned?

Sorry for making the tension, but I need this piece of code for the demo purposes. :) I can even contribute it myself, if you guys are too busy. Just want to be sure that we don't duplicate our work.

**Comment by sbunciak** [comment]
I think we need to sort out this topic on our call ;-)

We expect that the majority of his implementation work should be done by
the end of summer ( I know it's quite late for you, but he is a university
student, finishing his studies next year... ).
His assignment consists of imlementing SPI support in our Device API and
using it to control http://www.ti.com/product/lm74 (so it's mainly about
the SPI implementation and setting up a new camel component that can handle
this. As for the future, we want to extend capabilities of this component
to support I2C Temp.sensors and 1wire sensors as well.)

2015-05-08 13:05 GMT+02:00 Henryk Konsek <notifications@github.com>:

**Comment by sbunciak** [comment]
I started working on creating this component, supporting the 1wire sensors.
I will keep you updated.

2015-05-09 9:21 GMT+02:00 Štefan Bunčiak <pipistik.bunciak@gmail.com>:

**Comment by hekonsek** [comment]
This code [1] looks cool.

Actually I think we can name that component `camel-w1`. We prefer the components to be more specific in the naming.

Regarding the endpoint URI. I would imagine reading the temperature as follows:

    // polling consumer
    from("w1:label").to("mock:temp");
    // read on demand
    from("direct:readTemp").to("w1:label");

What do you think?

[1] https://github.com/px3/bulldog/blob/devel/bulldog-devices/src/main/java/io/silverspoon/bulldog/devices/sensors/DS18B20TemperatureSensor.java

**Comment by sbunciak** [comment]
I'm not 100% sure if it's a good idea to have camel-w1 component just to measure temperature. OneWire protocol has a broader range of use. 

We are going to have components like camel-pi4j & camel-bulldog which will provide all the bus implementations, and a common DSL for them. Thus, I'd prefer having a general temperature component that will leverage the common SPI as the DSL. Is it possible? What do you think about this proposal?

**Comment by sbunciak** [comment]
...and yes, I'm going to reuse the [1] class :-)

[1] https://github.com/px3/bulldog/blob/devel/bulldog-devices/src/main/java/io/silverspoon/bulldog/devices/sensors/DS18B20TemperatureSensor.java

**Comment by gautric** [comment]
hi @sbunciak,

please take a look to my i2c component (https://github.com/camel-labs/camel-labs/tree/master/iot/components/camel-pi4j/src/main/java/com/github/camellabs/component/pi4j/i2c) and BMP180 implementation (https://github.com/camel-labs/camel-labs/blob/master/iot/components/camel-pi4j/src/main/java/com/github/camellabs/component/pi4j/i2c/driver/BMP180Consumer.java)

you can use it directly via 

from("pi4j-i2c://1/0x77?driver=bmp180").to(WHERE_YOU_WANT_URI)

**Comment by hekonsek** [comment]
+1 for having generic temperature component. So the URI would look like:

    // polling consumer
    from("temperature:label").to("mock:temp");
    
    // read on demand
    from("temperature:readTemp").to("w1:label");

We can start by adding your class as a default implementation to `camel-temperature` component. We can refactor/move it later.

**Comment by sbunciak** [comment]
@hekonsek you can give it a try if you'd like:  https://github.com/px3/silverspoon/tree/devel/camel-temperature later we can move the component under rhiot repository.
Should you have any comments please let me know (sorry for the delay, my free time is almost none :-/ )

**Comment by hekonsek** [comment]
Closing old tickets. Feel free to reopen when you decide to contribute the code.
