### ISSUE TITLE
Create camel-openhab component

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#58]

**Comment by hekonsek** [comment]
@rnaszcyn mentioned that he played with OpenHAB. The contribution is more than welcome :) .

**Comment by rnaszcyn** [comment]
Now I just need to get myself started! The code skill atrophy I suffer from as a result of doing far more writing than coding over the past few years is something to overcome.

**Comment by hekonsek** [comment]
Fear not, we're here to support your efforts :) .

**Comment by gautric** [comment]
doc and ref : 
https://github.com/openhab
http://www.openhab.org/

**Comment by hekonsek** [comment]
Closing old tickets. Let's reopen it if we got actual code committed.
