### ISSUE TITLE
create camel-opencv component 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#64]
http://opencv.org/
the java lib

**Comment by hekonsek** [comment]
What can we actually do with this library? This is a kind of GUI library?

**Comment by gautric** [comment]
@hekonsek it is image processing library

**Comment by hekonsek** [comment]
Image processing? Like analyzing stuff from RPi camera?

wt., 12.05.2015 o 17:11 użytkownik Greg. A. <notifications@github.com>
napisał:

**Comment by gautric** [comment]
Yep

**Comment by hekonsek** [comment]
This is *awesome*!

wt., 12.05.2015 o 20:41 użytkownik Greg. A. <notifications@github.com>
napisał:

**Comment by hekonsek** [comment]
Moving this to the next release. I'd like to cut 0.0.0 release soon.

**Comment by gautric** [comment]
@hekonsek it isn't an IoT component, we should create new directory, any idea ?

**Comment by hekonsek** [comment]
I think that we can keep it in the 'compoennts' now to make it simpler. If
we got more components like this, we can try to move them to the dedicated
group. What do you think?

niedz., 31.05.2015 o 19:50 użytkownik Greg. A. <notifications@github.com>
napisał:

**Comment by hekonsek** [comment]
Closing old tickets. Let's reopen this when somebody would like to create the actual component.
