### ISSUE TITLE
create camel-raspistill component 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#65]
code for main code is here https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiStill.c
maybe we could wrap it into JNI stuff

**Comment by hekonsek** [comment]
Moving this to the next release. I'd like to cut 0.0.0 release soon.

**Comment by hekonsek** [comment]
Closing old tickets. Feel free to reopen the ticket if you would like to contribute the code.
