### ISSUE TITLE
Add support to detect explosive gases and LPG via sensors

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#69]
This might be cool for case studies.

**Comment by gautric** [comment]
we are looking for a beta tester, aren't we ?

**Comment by hekonsek** [comment]
Yeah, 100% test coverage got really serious here... ;)

czw., 14.05.2015 o 20:48 użytkownik Greg. A. <notifications@github.com>
napisał:

**Comment by hekonsek** [comment]
Closing old tickets. Let's reopen this when somebody would like to contribute the code.
