### ISSUE TITLE
Create Rhiot Raspbian OS

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#79]
we could create an OS img Raspbian based.
With Camel auto startup
Camel and/or RaspberryPi auto discovery
Camel Administration via hawtio
etc....
any other idea ?

**Comment by hekonsek** [comment]
Good idea. I was thinking that base image should contain Gateway [1] and our startup script [2]. Ideally I'd like to have a command line tool which could create new image like and write it to the SD card, so you can just insert the card into the laptop and execute: 

    write-camel-iot-gateway-image --SSID=mywifi:password --labs-version=0.1.0

Then you just insert the card into RPi and enjoy the running and connected Camel gateway. How cool would that be? :)

[1] https://github.com/camel-labs/camel-labs/blob/master/iot/readme.md#camel-iot-gateway
[2] https://github.com/camel-labs/camel-labs/blob/master/iot/readme.md#installing-gateway-on-the-raspbian

**Comment by hekonsek** [comment]
Actually now our CMD has `raspbian-install` command. I'm not sure if we need predefined image. I think that `raspbian-install` and additional CMD commands to install/configure Kura are just enough.

Feel free to reopen if you would like to commit some code.
