### ISSUE TITLE
Discuss conference talk

### ISSUE THREAD

**Issue by geertschuring** [rhiot/rhiot#81]
To generate more awareness about our efforts on using Camel in the IoT domain less discuss creating a conference talk. The CFP of ApacheCon Europe, Devoxx Belgium and Devoxx Morocco are currently open...

@hekonsek @davsclaus WDYT?

I have a talk called "*There's a Camel in my house*" which I gave at the IoT Developer Day in Utrecht. (http://www.developersday.nl/) We could take that as a starting point and go from there, or start from scratch and really think about what exactly we want we present.

**Comment by gautric** [comment]
you need French speaker for Devoxx Belgium and Devoxx Morocco ;-)
@geertschuring no pb to rebrand your work into Camel labs std, logo, typo etc...
we need to setup a full example cloudlet I think @hekonsek is working on

**Comment by geertschuring** [comment]
@gautric In my experience Devoxx Belgium is fully English. Don't know about Morocco, but the moroccan engineers I know all speak english rather well.

BTW, what do you mean with "no pb to rebrand..."?

**Comment by davsclaus** [comment]
There is JBC conf in barcelona that may be good for a CFP next year
http://www.jbcnconf.com/

**Comment by hekonsek** [comment]
I've been speaking at the ApacheCon EU last year and I'd love to talk again. This time including the IoT stuff. I'll submit to the CFP. I will also check

I will submit my "Internet of Things and the Back-end Developers" talk [1] for sure. I also plan to demonstrate Camel IoT Labs geofencing cloudlet together with the raspberry Pi. It has some nice Hawt.io based UI displaying the Google maps with the GPS data collected by the Pi :) . "Geofencing with the open source IoT software" or something like this :) . My "Eclipse Kura" talk [1] is the another candidate.

Geert - it will be awesome if you could deliver some "Smart home" related talk to the conferences. 

[1] https://iotcon.de/2015/sessions/internet-things-and-back-end-developers
[2] https://www.youtube.com/watch?v=mli5c-oTN1U

**Comment by geertschuring** [comment]
@hekonsek Yeah I'm sending proposels for my "Camel in the house" session, and also for a session together with Roel Hodzelmans which is focussed on collecting data and using OpenShift as a backend.

**Comment by jkirklan** [comment]
Any of you guys planning on going to EclipseCon in France?   I would go but it is the same week as RH summit...

**Comment by geertschuring** [comment]
@hekonsek Would you like to present together on ApacheCon? If you do the Kura part, I'll take my Tinkerforge/Camel stuff and we'd have an awesome session.

**Comment by gautric** [comment]
hi @jkirklan, 
I will be on holidays but I can split them to go to Toulouse,
I have to check with my manager and my GF too

**Comment by hekonsek** [comment]
EclipseCon collides with the plans of my wife. :(

@geertschuring We can think about dedicated "Camel IoT Labs overview" session for the ApacheCon. Regardless of my Kura and your Tinkerforge talk. What do you think?

**Comment by geertschuring** [comment]
@hekonsek Sounds like a plan!

**Comment by pax95** [comment]
@geertschuring eon would be fun. I have tried https://freeboard.io that has easy integration with pubnub.
![freeboard](https://cloud.githubusercontent.com/assets/775401/8011661/b7813008-0bba-11e5-88e6-688528a8e363.png)

**Comment by geertschuring** [comment]
@pax95 Thanks for the suggestion. Good stuff!

**Comment by pax95** [comment]
@geertschuring @hekonsek I got a http://www.pubnub.com/free-evangelism-program from PubNub for OSS dev. If anyone needs pub/sub key for demo/conference talks twitter DM @pax95

**Comment by hekonsek** [comment]
Noted!
