### ISSUE TITLE
Discuss target platform

### ISSUE THREAD

**Issue by geertschuring** [rhiot/rhiot#86]
Hey Guys,

We need to discuss what exactly is the target runtime platform that maven needs to build artifacts for. It defines the scope of the dependencies in the pom.
For instance, if we want to deploy the artifacts on Karaf, dependencies like camel and slf4j need the scope ```provided``` to make sure maven does not build artifacts (like feature files) that include these dependencies.

If maven needs to build some sort of fat jar though, the ```provided``` scope will screw that up.

**Comment by geertschuring** [comment]
@gautric Wauw you're fast with those labels :+1:

**Comment by hekonsek** [comment]
I would avoid making the dependencies OSGi-specific. I so would remove the provisioned scope from the  POM and leave compile scope. For the OSGi purposes, we should override these settings on the bundle plugin level. OSGi should be supported, but not affect the non-OSGi environments.

**Comment by geertschuring** [comment]
Agreed. I will make changes accordingly.

**Comment by hekonsek** [comment]
Actually I think that we could document the platforms we support. Like Karaf 4.x or our fat jar Gateway (which is a kinda platform as well).

**Comment by hekonsek** [comment]
Closing old tickets.
