### ISSUE TITLE
SNAPSHOT availability 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#87]
hi @hekonsek,

can we provide daily SNAPSHOT to maven central ?
it could be useful to accelerate integration and test process

best regards,

**Comment by hekonsek** [comment]
The project is `mvn deploy` ready, but I need to have a credentials to push snapshots to sonatype repos. Any idea have to add deploy step to the Travis CI process without exposing the password to the sonatype account?

**Comment by gautric** [comment]
@hekonsek I have got an internal server at home,
we could use it to deploy the daily SNAPSHOT

**Comment by hekonsek** [comment]
Yay! Can you create the Sonatype Jira account? I'll ask for permissions for you.

**Comment by hekonsek** [comment]
Hi @gautric. What was your Sonatype account name again? :)

**Comment by gautric** [comment]
the same "gautric" ;-)

**Comment by hekonsek** [comment]
I've just requested the deploy privileges for you :) .

**Comment by hekonsek** [comment]
You should be able to perform the releases now. Can you give it a try? And if everything works as expected, can you set up the daily SNAPSHOT builds on your home box?

**Comment by hekonsek** [comment]
I have granted you rights to deploy to the `io.rhiot` at Sonatype.

**Comment by hekonsek** [comment]
I have added snapshots deployments to Travis CI.
